### ISSUE TITLE
Implement file renaming

### ISSUE THREAD

**Issue by damondouglas** [damondouglas/startr.dart#3]

**Comment by enyo** [comment]
Do you have any timeline for this feature? This is crucial for us to generate polymer files. If you're too busy right now, I can give it a try, but it'll probably take me a lot longer than you.

**Comment by damondouglas** [comment]
@enyo I'll work on this now!  Yes, I was starting to use this tool and realized this is really necessary.  However, if you figure it out before me, feel free to PR.  Thank you for your interest!

**Comment by damondouglas** [comment]
@enyo done!  I tested this with

`$ startr clone git git@github.com:damondouglas/console-simple.dart.git`

**Comment by damondouglas** [comment]
@enyo , I think I'm missing a check when I've renamed the file already.

Unfortunately after updating to the new version:

`$ pub global deactivate startr`

`$ pub global activate startr`

I ran:

`$ startr clone git git@github.com:damondouglas/polymer-template.startr.dart.git`

and I got the following:
```
FileSystemException: Cannot open file, path = './EJgeNF/lib/__projectname__.dart' (OS Error: No such file or directory, errno = 2)
#0      CloneSubcommand.run.<run_async_body> (package:startr/src/clone.dart:64)
#1      _RootZone.runUnary (dart:async/zone.dart:1137)
#2      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:551)
#3      _Future._propagateToListeners (dart:async/future_impl.dart:637)
#4      _Future._complete (dart:async/future_impl.dart:414)
#5      _SyncCompleter.complete (dart:async/future_impl.dart:52)
#6      CloneSubcommand&Templatable.cleanUp.<anonymous closure>.<<anonymous closure>_async_body> (package:startr/src/clone.dart:310)
#7      _RootZone.runUnary (dart:async/zone.dart:1137)
#8      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:551)
#9      _Future._propagateToListeners (dart:async/future_impl.dart:637)
#10     _Future._completeWithValue (dart:async/future_impl.dart:424)
#11     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:479)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by enyo** [comment]
Great news on the progress. Have you figured out your problem?

**Comment by damondouglas** [comment]
@enyo done :)  Give it a try after:

`$ pub global deactivate startr`
`$ pub global activate startr`

with:

`$ startr clone git git@github.com:damondouglas/polymer-template.startr.dart.git`

**Comment by enyo** [comment]
Great! It worked thanks.

I'm having trouble with local files though. It doesn't seem to work when "cloning" path.

Also: what do you think about adding another option to specify a folder inside given repo. Right now we need to create individual repos for each template. It would be great if I could simply specify "folder `polymer/` in the repo".

**Comment by damondouglas** [comment]
@enyo, Thank you so much!  I reopened the issue.  May I trouble you to provide details of the problem with local files?  I will create better unittest cases hopefully and try to improve the project to satisfy those cases around the problem you discovered.  I created #7 to involve folders inside of a given repo.  I like this idea.
